// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v3.12.4
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { ObjectId } from "mongoose";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface PaginationDto {
  page: number;
  limit: number;
}

export interface Empty {
}

export interface FindOneUserDto {
  _id: string;
}

export interface CreateUserDto {
  name: string;
  username: string;
  email: string;
  password: string;
  mobile: string;
  city: string;
  state: string;
  district: string;
  village: string;
  pincode: string;
  role: string;
}

export interface UpdateUserDto {
  _id: string;
  name?: string | undefined;
  username?: string | undefined;
  email?: string | undefined;
  password?: string | undefined;
  mobile?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  district?: string | undefined;
  village?: string | undefined;
  pincode?: string | undefined;
  role?: string | undefined;
}

export interface UserResponse {
  _id: string;
  name: string;
  username: string;
  email: string;
  password: string;
  mobile: string;
  city: string;
  state: string;
  district: string;
  village: string;
  pincode: string;
  role: string;
}

export interface SocialMedia {
  facebook?: string | undefined;
  twitter?: string | undefined;
  instagram?: string | undefined;
  linkedin?: string | undefined;
}

export interface UsersResponse {
  users: UserResponse[];
}

export const AUTH_PACKAGE_NAME = "auth";

export interface UsersServiceClient {
  createUser(request: CreateUserDto): Observable<UserResponse>;

  findAllUsers(request: Empty): Observable<UsersResponse>;

  findOneUser(request: FindOneUserDto): Observable<UserResponse>;

  updateUser(request: UpdateUserDto): Observable<UserResponse>;

  deleteUser(request: FindOneUserDto): Observable<Empty>;

  queryUsers(request: Observable<PaginationDto>): Observable<UsersResponse>;
}

export interface UsersServiceController {
  createUser(request: CreateUserDto): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  findAllUsers(request: Empty): Promise<UsersResponse> | Observable<UsersResponse> | UsersResponse;

  findOneUser(request: FindOneUserDto): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUser(request: UpdateUserDto): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  deleteUser(request: FindOneUserDto): Promise<Empty> | Observable<Empty> | Empty;

  queryUsers(request: Observable<PaginationDto>): Observable<UsersResponse>;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "findAllUsers", "findOneUser", "updateUser", "deleteUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["queryUsers"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
